baseURL: https://zain-shahid.com
languageCode: en-us
title: "Zain Shahid"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1
  es:
    languageName: Spanish
    weight: 2

# Force a locale to be used, really useful to develop the application ! Should be commented in production, the "weight" should rocks.
# DefaultContentLanguage: en

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
# googleAnalytics: UA-XXXXXXXXX-X

# Enable Disqus forum
# disqusShortname: does-not-exist

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Background image of the landing page
  background: /img/background.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will default to the theme logos if not provided.
  logo:
    main: /img/logo.png
    inverted: /img/logo.png
    favicon: /img/favicon.ico

  # GitHub repo URL of your site
  gitRepo: https://gitlab.com/shahidzain67/

  # specify whether you want to write some blog posts or not
  enableBlogPost: false

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false
